# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the frontend source code to the container
COPY frontend/ .

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the frontend application
CMD ["npm", "start"]
