apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-05-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-05-frontend
  template:
    metadata:
      labels:
        app: episode-05-frontend
    spec:
      containers:
        - name: frontend
          image: episode-05-frontend:<tag>
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: episode-05-frontend-service
spec:
  selector:
    app: episode-05-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer