apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode-03-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-03-backend
  template:
    metadata:
      labels:
        app: episode-03-backend
    spec:
      containers:
        - name: backend
          image: episode-03-backend:<tag>
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: episode-03-backend-service
spec:
  selector:
    app: episode-03-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP